package se.arbetsformedlingen.skyddadesamtycken.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;

/**
 * Superclass representing an entity in the database with an autogenerated Id and a Version.
 */
@MappedSuperclass
public abstract class AbstractEntity {

  @Id
  @GeneratedValue
  @Column(name = "ID")
  protected Long id;

  @Version
  @Column(name = "VERSION")
  protected Long version;

  public Long getId() {
    return id;
  }
  protected void setId(Long id) {
    this.id = id;
  }

  public Long getVersion() {
    return version;
  }
  protected void setVersion(Long version) {
    this.version = version;
  }
}
